postgres:
    username: ENC[AES256_GCM,data:YaC4HQhZCTC+kCxGaoM=,iv:aQHOys+oW9ND3WLHt35KVvBLMELl2jtNz8/tj5FKEqc=,tag:fglqH6CS2Ka94Gc15yWMig==,type:str]
    password: ENC[AES256_GCM,data:S5EtfjXv5Evxox5gpDI=,iv:TsXmoayw33bSTGP1wgm9eGlvQA3BvcXOFPbPST37gbE=,tag:5ly7L3UrgY5k8ui0CIb4RA==,type:str]
    db: ENC[AES256_GCM,data:DweMFvHsM+Wp,iv:8GPGr3RP25vu64OzJHgls4Sk00pD06Dn76d81sc45SI=,tag:ANKANmcdt7uwLs7fG2+7bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fvcs2udlc5ucgvc5nvej468vrl34n0lahldgsne965z6f3cxcdsxffkr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VW1PamF1a1BsSmxnTm5h
            enhlRThmeVNPWGtwWWxjZklkY2h1czR1KzBVCmZzR0ZnRmpaSTZYU3Q4Vm44MVha
            ZmV4QUkzdWpNRlpRVXhYU25yZWRnSk0KLS0tIHR0QUxQR0d4b1gxU1RVTmtlbm00
            TGs3aGZMUzIxMm1mcCtkVURiR2VzZlUKpxMa0/Twu+q4TUuMxkD3MTDYjxMB9iF2
            UglR1pneUhrDL53Ry043UmEf6X8v3FMhJ7zMpVoWlM46TEalXbyHew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T18:51:36Z"
    mac: ENC[AES256_GCM,data:v15FNPuRDBM4U7QEL27lq2LjnI6tBnK1cV+oGbZmW+i3yG31eLnoDybBklnMV3Kg2c4UT1NdkK1RGPJzU4leF8JFsmH3YxpbtSPyejatlbr98bE5cj0G9DYhxuv1bUhciZZfHzZgCWQ9tBqvGTG/zLdhlInCJVU53rk1+GfVW6o=,iv:XR2a0E+1FO+eYevB2Gmy9NkoZmPgj7fTlBRIqTtKtRo=,tag:+KyvfNp1bbBwrxt+DfJsww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
