postgres:
    username: ENC[AES256_GCM,data:bPjLdpdYGZze,iv:Q5jH8+zFp/SiaXmpfDQk0IUzTuISTfmd4WRoip4OpI4=,tag:zw+oqnSLlPAwjZwbkDp2iQ==,type:str]
    password: ENC[AES256_GCM,data:mYVSj+wjBtFy,iv:Nw9Ltywy/txcspiQLP5cwVne4ftGl+CXe5jo8kiOhhk=,tag:SqFyeEOwf6jrihSjqOtX/g==,type:str]
    db: ENC[AES256_GCM,data:jwU6pQNPKqhQ,iv:MJ948Q0ckJqPwt10+KPslHSTj7wQIYqWD6q7CCDmUNk=,tag:EPGBrphRqg982f4RmGFsMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fvcs2udlc5ucgvc5nvej468vrl34n0lahldgsne965z6f3cxcdsxffkr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV1VKSGRvdjhTc3IwejV4
            K0ZuYWROV25CbFc3YmJVN0pia3JEMk5pL21nCit1ZWJ4RlpRNlZUYjhoY0g2OGh0
            V3IrNk10NWpmTjEwRVBqNEcwbTR0RFUKLS0tIDhCbllvNnpHbEladnd3eFBKQzVz
            OHdJTmJrUGpRN24vZ1ZmcWozOTlQTGcK2zE9p4+H3T/2xdU1mOfOeDcooXCMIei+
            p0vtdbnXzZJgdmDyQKgRxjNhlx5x3cC4W/3UVMM9eCJCyGgpd0oWrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:50:28Z"
    mac: ENC[AES256_GCM,data:EkJc9evGSrW6ySo1OR2RDitwAcp8HUdbi4FMpe2MHmtSoYjliYS9qj4fr8WjIZYP+lIJ7EDTOhFE0JgJTon2h6niJuFD3GeWIR3iKlk6SaSI6+vURaGm3dhmHQGoNLjb/V/TqFzI609ps+Jdc7ABeGSTcBSdBrkHh7+yDjeHMuU=,iv:16jVwKAuMfPV3VG0C46nBatZlJeC0O896Nm3hR94AYU=,tag:UaFRssqSBmJCgoVF2biwfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
