apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-db-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
