replicaCount: 2
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    # for prod we would use the following (which doesn't work due to rate limiting)
    #cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-prod-tls
      hosts:
        - api.baris.cloud-ip.cc
image:
  tag: v0.0.5
