image:
  repository: baris1892/datascientest-final-project-petclinic-rest
  pullPolicy: Always
  tag: "v0.0.5"

replicaCount: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: dev-api.baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-dev-tls
      hosts:
        - dev-api.baris.cloud-ip.cc
