image:
  repository: baris1892/datascientest-final-project-petclinic-rest
  pullPolicy: Always
  tag: "0e96c99d72a12978b49bf5788e931c443b66a2ca"
replicaCount: 1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: dev-api.baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-dev-tls
      hosts:
        - dev-api.baris.cloud-ip.cc
