image:
  repository: baris1892/datascientest-final-project-petclinic-rest
  pullPolicy: Always
  tag: "50d6c40419cc5b3324a04283605de14a0bc45cd4"
replicaCount: 1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: dev-api.baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-dev-tls
      hosts:
        - dev-api.baris.cloud-ip.cc
