server:
  service:
    type: ClusterIP

  ingress:
    enabled: false  # lokal erstmal port-forward

#  ingress:
#    enabled: true
#    ingressClassName: traefik
#    annotations:
#      cert-manager.io/cluster-issuer: letsencrypt-staging
#      traefik.ingress.kubernetes.io/router.entrypoints: websecure
#    hosts:
#      - argocd.dev.baris.cloud-ip.cc
#    tls:
#      - secretName: argocd-dev-tls
#        hosts:
#          - argocd.dev.baris.cloud-ip.cc

configs:
  params:
    server.insecure: true
