server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      # use https entrypoint
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - argocd.baris.cloud-ip.cc
    # leave it empty so cert manager doesn't look for certificates
    tls: []

configs:
  params:
    server.insecure: true
