image:
  repository: baris1892/datascientest-final-project-petclinic-angular
  pullPolicy: Always
  tag: "8346ab6fa715112b64b875c308cc0f6ed768f6f6"
replicaCount: 1
env:
  REST_API_URL: "https://dev-api.baris.cloud-ip.cc/petclinic/api/"
  ENV_NAME: "dev"
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: dev.baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-dev-tls
      hosts:
        - dev.baris.cloud-ip.cc
