replicaCount: 1

env:
  REST_API_URL: "https://api.baris.cloud-ip.cc/petclinic/api/"
  ENV_NAME: "prod"

ingress:
  hosts:
    - host: baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: frontend-prod-tls
      hosts:
        - baris.cloud-ip.cc
