replicaCount: 1

env:
  REST_API_URL: "https://dev-api.baris.cloud-ip.cc/petclinic/api/"
  ENV_NAME: "dev"

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: dev.baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-dev-tls # Muss mit dem Namen oben Ã¼bereinstimmen
      hosts:
        - dev.baris.cloud-ip.cc

# WORKS V1
#ingress:
#  className: traefik
#  annotations:
#    traefik.ingress.kubernetes.io/router.tls: "false"
#    traefik.ingress.kubernetes.io/router.tls.certresolver: ""
#    traefik.ingress.kubernetes.io/redirect-entry-point: ""
#  hosts:
#    - host: dev.baris.cloud-ip.cc
#      paths:
#        - path: /
#          pathType: Prefix

#ingress:
#  className: traefik
#  #  annotations:
#  #    cert-manager.io/cluster-issuer: letsencrypt
#  hosts:
#    - host: dev.baris.cloud-ip.cc
#      paths:
#        - path: /
#          pathType: Prefix
##  tls:
##    - secretName: frontend-dev-tls
##      hosts:
##        - dev.baris.cloud-ip.cc
