replicaCount: 1

env:
  REST_API_URL: "https://api.baris.cloud-ip.cc/petclinic/api/"
  ENV_NAME: "prod"

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging

    # for prod we would use the following (which doesn't work due to rate limiting)
    #cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-prod-tls
      hosts:
        - baris.cloud-ip.cc
