image:
  repository: baris1892/datascientest-final-project-petclinic-angular
  pullPolicy: Always
  tag: "6ef0cf143a7932a2b5cd88699d0031b7e18ce81b"
replicaCount: 1
env:
  REST_API_URL: "https://dev-api.baris.cloud-ip.cc/petclinic/api/"
  ENV_NAME: "dev"
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: dev.baris.cloud-ip.cc
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-dev-tls
      hosts:
        - dev.baris.cloud-ip.cc
