name: Docker Build, Scan and Push
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      context:
        required: false
        type: string
        default: "."
    outputs:
      image_tag:
        value: ${{ inputs.tag }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP 1: Build the image locally
      # We use 'load: true' to export the built image to the local Docker daemon.
      # This is crucial because security scanners like Trivy need to access
      # the image layers locally before they are pushed to a remote registry.
      # If we used 'push: true' here, we would skip the security gate.
      - name: Build Docker Image locally
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          push: false
          load: true
          tags: ${{ inputs.image_name }}:scan-tmp

      # STEP 2: Security Scan with Trivy
      # This scans the local image for OS-level vulnerabilities (CVEs).
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ inputs.image_name }}:scan-tmp'
          format: 'table'
          # exit-code: '0' ensures the pipeline continues even if issues are found.
          # ==> change to '1' to strictly block unsafe images.
          exit-code: 0
          severity: 'CRITICAL,HIGH'

      # STEP 3: Authentication
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # STEP 4: Final Push
      - name: Build and push verified image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ inputs.image_name }}:${{ inputs.tag }}
